language: c
sudo: required
dist: trusty
compiler:
  - gcc
# - clang
env:
#  - PGVERSION=9.4.7
  - PGVERSION=9.6.1

addons:
  apt:
    packages:
      - libperl-dev

# install PostgreSQL and start 2 clusters
before_install:
  - test/travis/install-pg.sh $PGVERSION

# install pgquarrel
install:
  - test/travis/install-pgquarrel.sh $PGVERSION

# create test databases
before_script:
  - test/travis/setup-pg.sh $PGVERSION

script:
  - test/travis/run-tests.sh $PGVERSION
