language: c
sudo: required
dist: xenial
compiler:
  - gcc
# - clang
env:
  - PGVERSION1=11 PGVERSION2=11

addons:
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - postgresql-contrib-11
      - postgresql-server-dev-11
      - postgresql-plperl-11
      - libpq-dev

# install pgquarrel
install:
  - test/travis/install-pgquarrel.sh $PGVERSION1 $PGVERSION2

# create test databases
before_script:
  - test/travis/setup-pg.sh $PGVERSION1 $PGVERSION2

# run tests
script:
  - test/travis/run-tests.sh $PGVERSION1 $PGVERSION2
