version: 0.7.{build}
image:
- Visual Studio 2019
configuration:
- Debug
- Release
services:
- postgresql15
before_build:
- cmd: cmake -B./build -DCMAKE_INSTALL_PREFIX=C:\pgquarrel -DCMAKE_PREFIX_PATH="C:\Program Files\PostgreSQL\15\bin"
build:
  verbosity: normal
